name: infrastructure configuration

on: workflow_dispatch

jobs: 
    configure-infra:
        runs-on: ubuntu-latest
        steps:
            - name: configure infra
              run: sleep 5
              shell : bash
            - name: iLo config
              run: sleep 4
              shell: bash
            - name: esxi config
              run: sleep 9
              shell: bash
    start-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: deploy servicenow
              run: sleep 6
              shell: bash